export const BUILDING_LOGOS = {
    educational_building: '/images/education.png',
    gate: '/images/door.png',
    dormitory: '/images/dorm.png',
    toilet: '/images/public_toilet.png',
    cafe: '/images/plate.png',
    kitchen: '/images/plate.png',
    post_office: '/images/delivery.png',
    supermarket: '/images/cart.png',
    drink: '/images/soft-drink.png',
    swimming_pool:'images/swimming.png',
    gym: '/images/gym.png',
    car: '/images/car.png',
    barber: '/images/barber.png',
    basketball_court: '/images/basketball.png',
    football_field: '/images/football.png',
    tennis_court: '/images/tennis.png',
    bridge: '/images/bridge.png',
    // library: '📚',
    // hospital: '🏥',
    // police: '👮',
    default: '/images/building.png'
};
